# Konfiguration für Endkunde
# Koordinaten sind in PDF-Punkten (1 Punkt = 1/72 Zoll ≈ 0.35mm)

qr_codes = [
  { x = 513.24, y = 620.17, size = 53.72, all_pages = true },
]

[positions]
vertreter_nummer = [
  { x = 146.89, y = 587.99, size = 16, all_pages = true, font_name = "Arial", font_size = 16, font_style = "Bold" },
  { x = 65.34, y = 52.52, size = 5.2, all_pages = true, font_name = "Calibri", font_size = 5.2, font_style = "Thin" },
]

